# Generated by Django 5.2.16 on 2026-09-30 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0137_add_gcd_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="show_discover",
            field=models.BooleanField(
                default=True,
                help_text="Show the Discover page and keep its caches warm",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="show_recommendations",
            field=models.BooleanField(
                default=True, help_text="Show recommendations on media detail pages"
            ),
        ),
    ]
